### ISSUE TITLE
ISSUE: 0.6.0 won't load

### ISSUE THREAD

**Issue by uSlackr** [FutureTense/keymaster#751]
### Describe the bug

Got this error after upgrading to 0.6.0.  I'm currentrly running HA 2026.9b1
error is:
Setup failed for custom integration 'keymaster': Unable to import component: cannot import name 'LARGE_LOCK_ACK_STORE_VERSION' from 'custom_components.keymaster.const' 

Log entry below.

### Home Assistant version

2026.9b1

### Keymaster version

0.6.0

### Home Assistant installation type

Home Assistant OS

### Lock provider

zwave_js

### Lock make and model

Yale YRD226 Z-wave

### Steps to reproduce

upgrade to 0.6.0
restart HA

### Expected behavior

Integration should load

### Logs

```text
Logger: homeassistant.setup
Source: setup.py:341
First occurred: 1:19:54 PM (1 occurrence)
Last logged: 1:19:54 PM

Setup failed for custom integration 'keymaster': Unable to import component: cannot import name 'LARGE_LOCK_ACK_STORE_VERSION' from 'custom_components.keymaster.const' (/config/custom_components/keymaster/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1095, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/keymaster/__init__.py", line 56, in <module>
    from .coordinator import KeymasterCoordinator
  File "/config/custom_components/keymaster/coordinator.py", line 66, in <module>
    from .helpers import (
    ...<6 lines>...
    )
  File "/config/custom_components/keymaster/helpers.py", line 19, in <module>
    from .const import (
    ...<17 lines>...
    )
ImportError: cannot import name 'LARGE_LOCK_ACK_STORE_VERSION' from 'custom_components.keymaster.const' (/config/custom_components/keymaster/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1055, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1047, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1095, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/keymaster/__init__.py", line 56, in <module>
    from .coordinator import KeymasterCoordinator
  File "/config/custom_components/keymaster/coordinator.py", line 66, in <module>
    from .helpers import (
    ...<6 lines>...
    )
  File "/config/custom_components/keymaster/helpers.py", line 19, in <module>
    from .const import (
    ...<17 lines>...
    )
ImportError: cannot import name 'LARGE_LOCK_ACK_STORE_VERSION' from 'custom_components.keymaster.const' (/config/custom_components/keymaster/const.py)
```

### Additional context

I downgraded to 0.5.3

**Comment by firstof9** [comment]
Thanks for reporting this!

We identified the root cause: the release packaging workflow in `.github/workflows/release.yaml` used an unanchored pattern when updating `VERSION = `, which accidentally matched and replaced `LARGE_LOCK_ACK_STORE_VERSION = 1` in `const.py` inside the published `keymaster.zip` asset.

Fix has been submitted in #752, and a hotfix release will be published shortly.

**Comment by uSlackr** [comment]
You are awesome.  Thanks so much for this quick fix!

**Comment by uSlackr** [comment]
Just stopping back to thank you for this tool.  I had to replace one of my locks today.  I installed it, added it to z-wave and added it to keymaster.  Made it a child of my backdoor lock and poof - all the codes and config are there.
So sweet!.  
Thanks again!

**Comment by firstof9** [comment]
Excellent! Enjoy!
